# -*- coding: utf-8 -*-
"""HTMLexpw8d1exercise3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kIzvlRwBaY3x8x3-DqciYznpXa1Gn4H0
"""

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
import pprint

options = webdriver.ChromeOptions()
options.add_argument('--headless')  # Run Chrome in headless mode
options.add_argument("--no-sandbox")  # Bypass OS security model
options.add_argument("--disable-dev-shm-usage")  # Overcome limited resource problems
driver = webdriver.Chrome(options=options)

url = "https://editorial.rottentomatoes.com/guide/movies-certified-fresh-verified-hot/"
driver.get(url)

wait = WebDriverWait(driver, 10)

soup = BeautifulSoup(driver.page_source, 'html.parser')
movies = soup.find_all(attrs={"data-qa": "discovery-media-list-item"})

for movie in movies:
    title_tag = movie.find("h2", class_="article_movie_title")
    score_tag = movie.find("span", class_="tMeterScore")
    year_tag = movie.find("span", class_="subtle start-year")

    title = title_tag.get_text(strip=True) if title_tag else "N/A"
    score = score_tag.get_text(strip=True) if score_tag else "N/A"
    year = year_tag.get_text(strip=True) if year_tag else "N/A"

    print(f"Title: {title}")
    print(f"Score: {score}")
    print(f"Release Year: {year}")
    print("-" * 40)

driver.quit()