# -*- coding: utf-8 -*-
"""HTMLexpw8d1exercise5ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nWHSowrzVM3vw4n4MQ4_Ap36m25Z5YOo
"""

!apt-get update > /dev/null
!apt install chromium-chromedriver > /dev/null
!pip install selenium beautifulsoup4 > /dev/null

import sys
sys.path.insert(0, '/usr/lib/chromium-browser/chromedriver')

!pip install selenium
!pip install bs4
!pip install chromedriver-autoinstaller

from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

driver.get("https://www.bbc.com/weather/293397")

wait = WebDriverWait(driver, 10)
html = driver.page_source

from bs4 import BeautifulSoup
soup = BeautifulSoup(html, "html.parser")
cards = soup.select(".wr-daycard")

data = []
for card in cards:
    date = card.select_one(".wr-date").get_text(strip=True)
    temp = card.select_one(".wr-day-temperature").get_text(strip=True)
    humidity = card.select_one(".wr-value--humidity__pct").get_text(strip=True)
    data.append({"date": date, "temp_C": temp, "condition": cond, "humidity": humidity})

import pandas as pd
from collections import Counter

df = pd.DataFrame(data)
df["temp_C"] = df["temp_C"].str.rstrip("°").astype(float)
df["humidity_pct"] = df["humidity"].str.rstrip("%").astype(float)
df["month"] = pd.to_datetime(df["date"] + " 2025", format="%a %d %Y").dt.strftime("%B")

avg_temp = df["temp_C"].mean().round(1)
common_condition = Counter(df["condition"]).most_common(1)[0][0]

import seaborn as sns
import matplotlib.pyplot as plt

sns.lineplot(data=df, x="date", y="temp_C", marker="o")
plt.title("Tel Aviv Daily Temperature (°C)")