# -*- coding: utf-8 -*-
"""HTMLexpw8d1exercise4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x9Rsr3sfwo4w3oVeyobPc8tUNctjQnIQ
"""

!apt-get update > /dev/null
!apt install chromium-chromedriver > /dev/null
!pip install selenium beautifulsoup4 > /dev/null

import sys
sys.path.insert(0, '/usr/lib/chromium-browser/chromedriver')

!pip install selenium
!pip install bs4
!pip install chromedriver-autoinstaller

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from bs4 import BeautifulSoup
from collections import defaultdict
from datetime import datetime

options = Options()
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
driver = webdriver.Chrome(options=options)

url = "https://www.bbc.com/innovation/technology"
driver.get(url)

WebDriverWait(driver, 10).until(
    EC.presence_of_all_elements_located((By.TAG_NAME, "article"))
)

soup = BeautifulSoup(driver.page_source, "html.parser")


articles = soup.find_all("article")

categorized = defaultdict(list)

for article in articles:
    title_tag = article.find("h2") or article.find("h3")
    date_tag = article.find("time")

    title = title_tag.get_text(strip=True) if title_tag else "No Title"
    date_str = date_tag.get("datetime") if date_tag else None


    if date_str:
        try:
            pub_date = datetime.fromisoformat(date_str)
            month = pub_date.strftime("%B")
        except:
            month = "Unknown"
    else:
        month = "Unknown"

    categorized[month].append(title)

driver.quit()

for month, titles in categorized.items():
    print(f"Month {month}:")
    for title in titles:
        print(f" - {title}")
    print("-" * 40)

