# -*- coding: utf-8 -*-
"""HTMLdailychallw7d5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19nxxJfo0jEi1gOuEgsQMy6kfKYd5kPX0
"""

from bs4 import BeautifulSoup
import requests

headers = {
    "User-Agent": "Mozilla/5.0"
}

html = requests.get("https://github.com/topics", headers=headers)

soup = BeautifulSoup(html.text, 'html.parser')

type(soup)
soup

if html.status_code == 200:
    html_content = html.text
    print("HTML content successfully fetched!\n")
    print(html_content[:1000])
    with open("webpage.html", "w", encoding=html.encoding if html.encoding else "utf-8") as file:
        file.write(html_content)
else:
    print(f"Failed to fetch content. Status code: {html.status_code}")

with open("webpage.html", "r", encoding="utf-8") as f:
    soup2 = BeautifulSoup(f, "html.parser")

print(soup2.prettify())

soup2.html.head.title

titles = [tag.text.strip() for tag in soup.find_all("p", class_="f3 lh-condensed mb-0 mt-1 Link--primary")]
descriptions = [tag.text.strip() for tag in soup.find_all("p", class_="f5 color-fg-muted mb-0 mt-1")]

print("Number of titles:", len(titles))
print("Number of descriptions:", len(descriptions))
print("\nSample titles:", titles[:3])
print("\nSample descriptions:", descriptions[:3])

data = {
    "title": titles,
    "description": descriptions}

import pandas as pd

df = pd.DataFrame(data)

print("\nDataFrame Preview:")
print(df.head())