# -*- coding: utf-8 -*-
"""DailyChallW7D4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYdN8gZ-s84k0omswxaGxUQSxS6_wHjv
"""

import pandas as pd
import openpyxl
from openpyxl import Workbook
from openpyxl.styles import PatternFill
from openpyxl.styles import Font
from string import ascii_uppercase

wb = Workbook()
ws = wb.active

ws.title = "Grades"

data = [
    ["Name", "Math", "Science", "English", "Gym"],
    ["Joe", 65, 78, 98, 89],
    ["Bill", 55, 72, 87, 95],
    ["Tim", 100, 45, 75, 92],
    ["Sally", 30, 25, 45, 100],
    ["Jane", 100, 100, 100, 60]]

for row in data:
    ws.append(row)


for col in ascii_uppercase[1:5]:
    ws[f"{col}7"] = f"=AVERAGE({col}2:{col}6)"

for col in ascii_uppercase[:5]:
    cell = ws[f"{col}1"]
    cell.font = Font(bold=True)
    cell.fill = PatternFill("solid", fgColor="FFFF00")

wb.save("Grades.xlsx")